In [8]:
import pandas as pd

df=pd.read_csv(r'HIV_NYC_GWR.csv')
df = df.drop(columns = ['HIV_Case_log'])
df.head()

,geoid,X,Y,HIV_Case,HIV_Rate,M_housing_costs,%_with_4year_college_degree,%_unemployed,%_manufacturing,%_below_poverty,...,%_owner_housing,%_multiunit_structures,%_<_18_years_old,%_black,%_white,%_Hispanic,%_Asian,%_foreign_born,%_health_insurance,%_no_health_insurance
0,10001,-73.9971,40.7507,4698,928,1817,37.864887,3.514080,2.138100,13.263494,...,26.168450,90.298447,8.650323,6.163846,62.912232,14.159832,25.187576,32.341651,94.269258,5.730742
1,10002,-73.9862,40.7158,1230,885,980,21.852603,4.919751,3.746494,27.657486,...,13.327370,78.604651,13.287907,8.378115,32.227008,27.189204,41.455869,41.838572,91.500380,8.499620
2,10003,-73.9892,40.7318,1477,787,2190,42.439063,4.026729,2.383478,8.453640,...,32.939060,93.917471,7.090084,5.811784,75.913463,8.240372,13.483413,19.871256,94.862022,5.137978
3,10004,-74.0130,40.7038,1271,35,3236,47.506871,3.201970,2.372881,2.179657,...,38.276070,94.575045,11.393659,1.684280,62.813738,3.698811,30.449141,27.443857,95.114943,4.885057
4,10005,-74.0089,40.7061,946,64,3238,48.451260,2.877036,1.717187,9.511947,...,19.638775,95.176040,12.535387,2.502548,73.423168,6.884838,16.951648,22.319103,97.398844,2.601156

In [9]:
df3 = df.drop(columns=['geoid', 'HIV_Case', 'HIV_Rate', 'X', 'Y'])
df3

,M_housing_costs,%_with_4year_college_degree,%_unemployed,%_manufacturing,%_below_poverty,%_houses_30_old,%_households_moved_<10_years_ago,%_>_60_years_old,%_service_industry,%_vacant_housing,%_owner_housing,%_multiunit_structures,%_<_18_years_old,%_black,%_white,%_Hispanic,%_Asian,%_foreign_born,%_health_insurance,%_no_health_insurance
0,1817,37.864887,3.514080,2.138100,13.263494,60.688777,56.768879,21.047810,10.459166,12.092497,26.168450,90.298447,8.650323,6.163846,62.912232,14.159832,25.187576,32.341651,94.269258,5.730742
1,980,21.852603,4.919751,3.746494,27.657486,88.299183,34.454826,28.253304,25.204243,6.113537,13.327370,78.604651,13.287907,8.378115,32.227008,27.189204,41.455869,41.838572,91.500380,8.499620
2,2190,42.439063,4.026729,2.383478,8.453640,90.238373,53.661991,16.921473,8.048917,15.390595,32.939060,93.917471,7.090084,5.811784,75.913463,8.240372,13.483413,19.871256,94.862022,5.137978
3,3236,47.506871,3.201970,2.372881,2.179657,68.162693,65.211640,13.705416,2.421308,22.440393,38.276070,94.575045,11.393659,1.684280,62.813738,3.698811,30.449141,27.443857,95.114943,4.885057
4,3238,48.451260,2.877036,1.717187,9.511947,74.001791,89.936465,1.664591,2.687771,21.683080,19.638775,95.176040,12.535387,2.502548,73.423168,6.884838,16.951648,22.319103,97.398844,2.601156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,1329,15.586385,6.661419,3.044917,21.438192,74.220374,45.945022,17.581304,30.799888,6.923981,24.104108,53.641837,30.670403,46.837273,38.931946,26.363013,3.499568,30.464721,87.627243,12.372757
173,1272,15.359058,9.583996,3.015010,25.432123,70.138983,52.202884,17.312181,27.756211,8.042100,34.306676,42.171680,28.221619,60.892764,22.604926,24.400934,5.711972,31.780287,90.759186,9.240814
174,1108,15.699238,4.058774,2.415848,14.042220,75.518063,36.555054,19.235235,29.650507,11.149826,50.691434,51.558308,21.913461,19.900921,63.271151,29.491447,4.032820,25.419924,93.159099,6.840901
175,1450,23.915614,3.543814,1.841085,9.885352,90.887063,38.145881,28.050951,14.717916,10.788032,53.200283,54.251299,19.630982,6.785614,81.305610,14.905872,3.474759,14.685773,94.756765,5.243235
176,1149,28.148740,3.491544,1.548822,3.107345,51.782217,29.278642,33.672316,16.565657,46.533490,96.849817,1.318681,21.779661,0.593220,95.423729,6.468927,0.564972,2.796610,98.854337,1.145663

In [10]:
# Import library for VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor

def calc_vif(X):

    # Calculating VIF
    vif = pd.DataFrame()
    vif["variables"] = X.columns
    vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

    return(vif)

In [11]:
X = df3.iloc[:,:]
calc_vif(X)

                           variables          VIF
0                    M_housing_costs   101.471313
1        %_with_4year_college_degree    13.510889
2                       %_unemployed     3.013233
3                    %_manufacturing     2.008072
4                    %_below_poverty     7.865631
5                    %_houses_30_old     2.440215
6   %_households_moved_<10_years_ago     7.320600
7                   %_>_60_years_old     4.321977
8                 %_service_industry    19.219917
9                   %_vacant_housing     2.073859
10                   %_owner_housing    16.508298
11            %_multiunit_structures    12.521455
12                  %_<_18_years_old     2.976420
13                           %_black    27.207283
14                           %_white    26.765024
15                        %_Hispanic    10.985062
16                           %_Asian    12.414756
17                    %_foreign_born     4.980300
18                %_health_insurance  1203.367126
19             %_no_health_insurance    42.465231

In [13]:
# remove'% health insurance'
df2 = df.drop(columns=['geoid', 'X', 'Y', 'HIV_Case', 'HIV_Rate', '%_health_insurance'])
df2

,M_housing_costs,%_with_4year_college_degree,%_unemployed,%_manufacturing,%_below_poverty,%_houses_30_old,%_households_moved_<10_years_ago,%_>_60_years_old,%_service_industry,%_vacant_housing,%_owner_housing,%_multiunit_structures,%_<_18_years_old,%_black,%_white,%_Hispanic,%_Asian,%_foreign_born,%_no_health_insurance
0,1817,37.864887,3.514080,2.138100,13.263494,60.688777,56.768879,21.047810,10.459166,12.092497,26.168450,90.298447,8.650323,6.163846,62.912232,14.159832,25.187576,32.341651,5.730742
1,980,21.852603,4.919751,3.746494,27.657486,88.299183,34.454826,28.253304,25.204243,6.113537,13.327370,78.604651,13.287907,8.378115,32.227008,27.189204,41.455869,41.838572,8.499620
2,2190,42.439063,4.026729,2.383478,8.453640,90.238373,53.661991,16.921473,8.048917,15.390595,32.939060,93.917471,7.090084,5.811784,75.913463,8.240372,13.483413,19.871256,5.137978
3,3236,47.506871,3.201970,2.372881,2.179657,68.162693,65.211640,13.705416,2.421308,22.440393,38.276070,94.575045,11.393659,1.684280,62.813738,3.698811,30.449141,27.443857,4.885057
4,3238,48.451260,2.877036,1.717187,9.511947,74.001791,89.936465,1.664591,2.687771,21.683080,19.638775,95.176040,12.535387,2.502548,73.423168,6.884838,16.951648,22.319103,2.601156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,1329,15.586385,6.661419,3.044917,21.438192,74.220374,45.945022,17.581304,30.799888,6.923981,24.104108,53.641837,30.670403,46.837273,38.931946,26.363013,3.499568,30.464721,12.372757
173,1272,15.359058,9.583996,3.015010,25.432123,70.138983,52.202884,17.312181,27.756211,8.042100,34.306676,42.171680,28.221619,60.892764,22.604926,24.400934,5.711972,31.780287,9.240814
174,1108,15.699238,4.058774,2.415848,14.042220,75.518063,36.555054,19.235235,29.650507,11.149826,50.691434,51.558308,21.913461,19.900921,63.271151,29.491447,4.032820,25.419924,6.840901
175,1450,23.915614,3.543814,1.841085,9.885352,90.887063,38.145881,28.050951,14.717916,10.788032,53.200283,54.251299,19.630982,6.785614,81.305610,14.905872,3.474759,14.685773,5.243235
176,1149,28.148740,3.491544,1.548822,3.107345,51.782217,29.278642,33.672316,16.565657,46.533490,96.849817,1.318681,21.779661,0.593220,95.423729,6.468927,0.564972,2.796610,1.145663

In [14]:
X = df2.iloc[:,:]
calc_vif(X)

                           variables         VIF
0                    M_housing_costs   87.161026
1        %_with_4year_college_degree   73.532691
2                       %_unemployed   19.849734
3                    %_manufacturing   16.043242
4                    %_below_poverty   26.010449
5                    %_houses_30_old   52.816751
6   %_households_moved_<10_years_ago  109.925284
7                   %_>_60_years_old   45.611119
8                 %_service_industry   97.830709
9                   %_vacant_housing    7.503561
10                   %_owner_housing   53.067043
11            %_multiunit_structures  107.795430
12                  %_<_18_years_old   37.735957
13                           %_black   28.267922
14                           %_white   71.346029
15                        %_Hispanic   21.082272
16                           %_Asian   18.993826
17                    %_foreign_born   45.072606
18             %_no_health_insurance   22.936753

In [27]:
import numpy as np

# %without health insurance
# %vacant housing
# %below poverty
# %unemployed
df_independent = df[['%_no_health_insurance', '%_below_poverty', '%_vacant_housing', '%_white']]
print(calc_vif(df_independent))

# correlation coefficient matrix
cc_matrix = pd.DataFrame(np.corrcoef(df_independent.transpose()))
cc_matrix.columns = df_independent.columns
cc_matrix.index = df_independent.columns
cc_matrix

               variables       VIF
0  %_no_health_insurance  5.417664
1        %_below_poverty  5.128134
2       %_vacant_housing  4.044931
3                %_white  3.864730

,%_no_health_insurance,%_below_poverty,%_vacant_housing,%_white
%_no_health_insurance,1.000000,0.548403,-0.360896,-0.550377
%_below_poverty,0.548403,1.000000,-0.331945,-0.535474
%_vacant_housing,-0.360896,-0.331945,1.000000,0.433130
%_white,-0.550377,-0.535474,0.433130,1.000000

In [26]:


# correlation coefficient matrix
cc_matrix = pd.DataFrame(np.corrcoef(df2.transpose()))
cc_matrix.columns = df2.columns
cc_matrix.index = df2.columns
cc_matrix

,Median monthly housing costs,% unemployed,% manufacturing,% below poverty,% structures more than 30 years old,% > 60 years old,% service industry,% vacant housing,% owner occupied housing,% < 18 years old,% black,% white,% Hispanic,% Asian,% foreign born,% without health insurance
Median monthly housing costs,1.000000,-0.533170,-0.255333,-0.632046,-0.540123,-0.249054,-0.753577,0.520445,0.127514,-0.443555,-0.324283,0.481485,-0.512957,0.174332,-0.208279,-0.522785
% unemployed,-0.533170,1.000000,0.005990,0.591709,0.258691,-0.196535,0.653175,-0.416844,-0.309294,0.437212,0.570271,-0.663184,0.459315,-0.374039,0.124051,0.345892
% manufacturing,-0.255333,0.005990,1.000000,0.171964,0.259847,0.002847,0.185774,-0.228507,0.006490,0.152520,-0.353862,0.001734,0.320349,0.336552,0.367286,0.404061
% below poverty,-0.632046,0.591709,0.171964,1.000000,0.111123,-0.372792,0.714198,-0.331945,-0.643191,0.532826,0.332508,-0.535474,0.655854,-0.286268,0.092171,0.548403
% structures more than 30 years old,-0.540123,0.258691,0.259847,0.111123,1.000000,0.315193,0.349559,-0.414673,0.070121,0.010793,0.182511,-0.302955,0.206269,-0.002547,0.307685,0.312791
% > 60 years old,-0.249054,-0.196535,0.002847,-0.372792,0.315193,1.000000,-0.175115,-0.053983,0.532699,-0.284602,-0.131092,0.227139,-0.332934,0.178112,0.003498,-0.272370
% service industry,-0.753577,0.653175,0.185774,0.714198,0.349559,-0.175115,1.000000,-0.503235,-0.239439,0.623697,0.515772,-0.766748,0.693537,-0.214129,0.440008,0.753670
% vacant housing,0.520445,-0.416844,-0.228507,-0.331945,-0.414673,-0.053983,-0.503235,1.000000,-0.028813,-0.404485,-0.285742,0.433130,-0.317451,0.051634,-0.255671,-0.360896
% owner occupied housing,0.127514,-0.309294,0.006490,-0.643191,0.070121,0.532699,-0.239439,-0.028813,1.000000,-0.029420,-0.096387,0.225747,-0.450126,0.209468,-0.047530,-0.310772
% < 18 years old,-0.443555,0.437212,0.152520,0.532826,0.010793,-0.284602,0.623697,-0.404485,-0.029420,1.000000,0.322785,-0.409322,0.415545,-0.251023,0.091271,0.401497
% black,-0.324283,0.570271,-0.353862,0.332508,0.182511,-0.131092,0.515772,-0.285742,-0.096387,0.322785,1.000000,-0.749511,0.041786,-0.500564,-0.007382,0.137177
% white,0.481485,-0.663184,0.001734,-0.535474,-0.302955,0.227139,-0.766748,0.433130,0.225747,-0.409322,-0.749511,1.000000,-0.412725,0.057381,-0.461678,-0.550377
% Hispanic,-0.512957,0.459315,0.320349,0.655854,0.206269,-0.332934,0.693537,-0.317451,-0.450126,0.415545,0.041786,-0.412725,1.000000,-0.259263,0.234273,0.644187
% Asian,0.174332,-0.374039,0.336552,-0.286268,-0.002547,0.178112,-0.214129,0.051634,0.209468,-0.251023,-0.500564,0.057381,-0.259263,1.000000,0.556976,0.132718
% foreign born,-0.208279,0.124051,0.367286,0.092171,0.307685,0.003498,0.440008,-0.255671,-0.047530,0.091271,-0.007382,-0.461678,0.234273,0.556976,1.000000,0.633367
% without health insurance,-0.522785,0.345892,0.404061,0.548403,0.312791,-0.272370,0.753670,-0.360896,-0.310772,0.401497,0.137177,-0.550377,0.644187,0.132718,0.633367,1.000000